version: '3'

services:
  mongo:
    container_name: mongo-container
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  api:
    container_name: api-container
    build: .
    image: api
    command: npm run dev
    volumes:
      - ./:/usr/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo