version: '3'

services:
  mongo:
    container_name: mongo-container
    image: mongo
    volumes:
      - ./docker-volumes/:/data/db
    ports:
      - "27017:27017"
    external_links:
      - mongo

  api:
    container_name: api-container
    build: .
    image: api
    command: npm run dev
    volumes:
      - ./docker-volumes/:/usr/app
    ports:
      - "3000:3000"
      - "9222:9222"
    depends_on:
      - mongo